// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieAPI.Models;

namespace MovieAPI.Migrations
{
    [DbContext(typeof(MovieAPIContext))]
    [Migration("20210627224020_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MovieAPI.Models.Actor", b =>
                {
                    b.Property<int>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("OscarWinner")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ActorId");

                    b.HasIndex("MovieId");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            ActorId = 1,
                            Age = 57,
                            MovieId = 1,
                            Name = "Nicolas Cage",
                            OscarWinner = true
                        },
                        new
                        {
                            ActorId = 2,
                            Age = 67,
                            MovieId = 1,
                            Name = "John Malkovich",
                            OscarWinner = true
                        },
                        new
                        {
                            ActorId = 3,
                            Age = 46,
                            MovieId = 2,
                            Name = "Angelina Jolie",
                            OscarWinner = true
                        },
                        new
                        {
                            ActorId = 4,
                            Age = 53,
                            MovieId = 3,
                            Name = "Daniel Craig",
                            OscarWinner = true
                        },
                        new
                        {
                            ActorId = 5,
                            Age = 86,
                            MovieId = 3,
                            Name = "Judi Dench",
                            OscarWinner = true
                        },
                        new
                        {
                            ActorId = 6,
                            Age = 90,
                            MovieId = 5,
                            Name = "Sean Connery",
                            OscarWinner = true
                        },
                        new
                        {
                            ActorId = 7,
                            Age = 70,
                            MovieId = 5,
                            Name = "Ed Harris",
                            OscarWinner = true
                        },
                        new
                        {
                            ActorId = 8,
                            Age = 66,
                            MovieId = 6,
                            Name = "Denzel Washington",
                            OscarWinner = true
                        },
                        new
                        {
                            ActorId = 9,
                            Age = 48,
                            MovieId = 6,
                            Name = "Ryan Hurst",
                            OscarWinner = true
                        },
                        new
                        {
                            ActorId = 10,
                            Age = 43,
                            MovieId = 7,
                            Name = "Kumail Nanjiani",
                            OscarWinner = false
                        },
                        new
                        {
                            ActorId = 11,
                            Age = 31,
                            MovieId = 7,
                            Name = "Zoe Kazan",
                            OscarWinner = true
                        },
                        new
                        {
                            ActorId = 12,
                            Age = 58,
                            MovieId = 8,
                            Name = "Steve Carell",
                            OscarWinner = true
                        },
                        new
                        {
                            ActorId = 13,
                            Age = 40,
                            MovieId = 8,
                            Name = "Ryan Gosling",
                            OscarWinner = true
                        },
                        new
                        {
                            ActorId = 14,
                            Age = 51,
                            MovieId = 9,
                            Name = "Gerard Butler",
                            OscarWinner = false
                        },
                        new
                        {
                            ActorId = 15,
                            Age = 43,
                            MovieId = 9,
                            Name = "Pablo Schreiber",
                            OscarWinner = false
                        },
                        new
                        {
                            ActorId = 16,
                            Age = 53,
                            MovieId = 10,
                            Name = "Vin Diesel",
                            OscarWinner = false
                        },
                        new
                        {
                            ActorId = 17,
                            Age = 40,
                            MovieId = 10,
                            Name = "Paul Walker",
                            OscarWinner = false
                        });
                });

            modelBuilder.Entity("MovieAPI.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Director = "Simon West",
                            Genre = "Action",
                            Name = "Con Air",
                            Rating = 7.0,
                            Year = 1997
                        },
                        new
                        {
                            MovieId = 2,
                            Director = "Dominic Sena",
                            Genre = "Action",
                            Name = "Gone in 60 Seconds",
                            Rating = 6.7000000000000002,
                            Year = 2000
                        },
                        new
                        {
                            MovieId = 3,
                            Director = "Sam Mendes",
                            Genre = "Action",
                            Name = "Skyfall",
                            Rating = 7.7000000000000002,
                            Year = 2012
                        },
                        new
                        {
                            MovieId = 4,
                            Director = "Sam Mendes",
                            Genre = "Drama",
                            Name = "1917",
                            Rating = 7.7999999999999998,
                            Year = 2020
                        },
                        new
                        {
                            MovieId = 5,
                            Director = "Michael Bay",
                            Genre = "Action",
                            Name = "The Rock",
                            Rating = 7.5,
                            Year = 1996
                        },
                        new
                        {
                            MovieId = 6,
                            Director = "Boaz Yakin",
                            Genre = "Drama",
                            Name = "Remember The Titans",
                            Rating = 8.0,
                            Year = 2000
                        },
                        new
                        {
                            MovieId = 7,
                            Director = "Michael Showalter",
                            Genre = "Romantic Comedy",
                            Name = "The Big Sick",
                            Rating = 7.7000000000000002,
                            Year = 2017
                        },
                        new
                        {
                            MovieId = 8,
                            Director = "Adam McKay",
                            Genre = "Drama",
                            Name = "The Big Short",
                            Rating = 8.0,
                            Year = 2015
                        },
                        new
                        {
                            MovieId = 9,
                            Director = "Christian Gudegast",
                            Genre = "Action",
                            Name = "Den of Thieves",
                            Rating = 7.0,
                            Year = 2018
                        },
                        new
                        {
                            MovieId = 10,
                            Director = "Justin Lin",
                            Genre = "Action",
                            Name = "Fast Five",
                            Rating = 7.5,
                            Year = 2011
                        });
                });

            modelBuilder.Entity("MovieAPI.Models.Actor", b =>
                {
                    b.HasOne("MovieAPI.Models.Movie", null)
                        .WithMany("Actors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieAPI.Models.Movie", b =>
                {
                    b.Navigation("Actors");
                });
#pragma warning restore 612, 618
        }
    }
}
